[package]
name = "primitives"
version = "0.1.0"
edition = "2021"

[dependencies]
crossbeam = "0.8"
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { verison = "1", features = ["sync"] }